---
title: "ggplot.remake"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# rho = 0.8
```{r}
testtable.8 <- getplot.rho(0.8)
ef.8 <- ef.table.fuc(testtable.8, 0.8)
df.8 <- df.table.fuc(testtable.8)

p1.8 <- ggplot(ef.8, aes(x, y, colour = int, linetype=int)) +
  geom_line(size = 1.5) +
 scale_color_manual(name = "Sampling method", values = c("red", "blue", "red", "blue")) +
scale_linetype_manual(name = "Sampling method", values = c(2,2,1,1)) +
  xlab('') +
  ylab('Relative efficiency') +
 labs(title = "Relative efficiency vs. subcohort size", subtitle = "Rho = 0.8") +
   theme_classic() +
     theme(axis.title.y = element_text(size = 20),
                 axis.text.x = element_text(size = 17),
                 axis.text.y = element_text(size = 17),
           plot.title  = element_text(size = 35),
           plot.subtitle = element_text(size = 25),
           legend.title=element_text(size=20),
           legend.text=element_text(size=17),
            legend.position = c(0.8, 0.2))
##########
p2.8 <- ggplot(df.8, aes(x, y, colour = int, linetype=int)) +
  geom_line(size = 1.5) +
 scale_color_manual(name = "Sampling method", values = c("red", "blue", "red", "blue")) +
scale_linetype_manual(name = "Sampling method", values = c(2,2,1,1)) +
  xlab('') +
  ylab('Variance') +
 labs(title = "Variance vs. subcohort size", subtitle = "Rho = 0.8") +
   theme_classic() +
     theme(axis.title.y = element_text(size = 20),
                 axis.text.x = element_text(size = 17),
                 axis.text.y = element_text(size = 17),
           plot.title  = element_text(size = 35),
           plot.subtitle = element_text(size = 25),
           legend.title=element_text(size=20),
           legend.text=element_text(size=17),
            legend.position = c(0.8, 0.8))
           
grid.arrange(p1.8,p2.8, ncol=2,
             bottom=textGrob("Subcohort size (100 - 500)", gp=gpar(fontsize=30)))      
```

```{r}
ef.7 <- ef.table.fuc(testtable.7, 0.7)
df.7 <- df.table.fuc(testtable.7)

p1.7 <- ggplot(ef.7, aes(x, y, colour = int, linetype=int)) +
  geom_line(size = 1.5) +
 scale_color_manual(name = "Sampling method", values = c("red", "blue", "red", "blue")) +
scale_linetype_manual(name = "Sampling method", values = c(2,2,1,1)) +
  xlab('') +
  ylab('Relative efficiency') +
 labs(title = "Relative efficiency vs. subcohort size", subtitle = "Rho = 0.7") +
   theme_classic() +
     theme(axis.title.y = element_text(size = 20),
                 axis.text.x = element_text(size = 17),
                 axis.text.y = element_text(size = 17),
           plot.title  = element_text(size = 35),
           plot.subtitle = element_text(size = 25),
           legend.title=element_text(size=20),
           legend.text=element_text(size=17),
            legend.position = c(0.8, 0.2))
##########
p2.7 <- ggplot(df.7, aes(x, y, colour = int, linetype=int)) +
  geom_line(size = 1.5) +
 scale_color_manual(name = "Sampling method", values = c("red", "blue", "red", "blue")) +
scale_linetype_manual(name = "Sampling method", values = c(2,2,1,1)) +
  xlab('') +
  ylab('Variance') +
 labs(title = "Variance vs. subcohort size", subtitle = "Rho = 0.7") +
   theme_classic() +
     theme(axis.title.y = element_text(size = 20),
                 axis.text.x = element_text(size = 17),
                 axis.text.y = element_text(size = 17),
           plot.title  = element_text(size = 35),
           plot.subtitle = element_text(size = 25),
           legend.title=element_text(size=20),
           legend.text=element_text(size=17),
            legend.position = c(0.8, 0.8))
           
grid.arrange(p1.7,p2.7, ncol=2,
             bottom=textGrob("Subcohort size (100 - 500)", gp=gpar(fontsize=30)))   



















```